# docker-compose.yml
version: '3.8'

services:
 ai-bot:
   build: .
   restart: unless-stopped
   deploy:
     resources:
      limits:
       cpus: '0.25'
       memory: 256M
      reservations:
       cpus: '0.1'
       memory: 128M
