# docker-compose.yml
services:
 ai-bot:
   image: stainlesteel/ai-discord-bot:latest
   restart: unless-stopped
   deploy:
     resources:
      limits:
       cpus: '0.25'
       memory: 256M
      reservations:
       cpus: '0.1'
       memory: 128M
