# docker-compose.yml
# DISCORD_TOKEN= for the discord developers api key
# GEMINI_TOKEN= gemini api free tier has restrictions
# SYS_INS= you can add custom message instructions for gemini

services:
 ai-bot:
   build: .
   image: stainlesteel/ai-discord-bot:latest
   restart: unless-stopped
   environment:
       DISCORD_TOKEN: 
       GEMINI_TOKEN:
       SYS_INS: | # add a string below
   deploy:
     resources:
      limits:
       cpus: '0.25'
       memory: 256M
      reservations:
       cpus: '0.1'
       memory: 128M
